### PR TITLE
#60 Ensure local config changes stay local

### PR DESCRIPTION
**Pull request by bdimaggio**
Make our local config-split call to a config split called config_local rather than local.

### CODE REVIEW

**Comment by bdimaggio** [comment]
Hey @unclegcb or @maria-thinkshout, could one of you take a look at this? Details [here](https://github.com/thinkshout/robo-drupal/issues/60). I'll happily make the corresponding changes in our drupal-project if this all makes sense.

**Comment by mariacha** [comment]
@bdimaggio Makes sense to me, but could we also go the other way and make the folder/settings.php changes in the drupal project reference "local"?

**Comment by bdimaggio** [comment]
@mariacha certainly. My reasoning for `config_local` that it might be a clearer folder name for devs encountering a project's git root for the first time (it'd have a clear relationship to the `config` dir they also see there), but I'm not picky.

**Comment by mariacha** [comment]
I like that logic and would agree with it, but the problem is with backwards compatibility. There are currently 18 projects using the "local" config name:
https://github.com/search?q=org%3Athinkshout+config_split.config_split.local&type=Code

And the only freedom house is using config_local (excluding uchi, which I switched over at one point so it's using "both")
https://github.com/search?q=org%3Athinkshout+config_split.config_split.config_local&type=Code

So it will cause a lot fewer headaches if we use local here and switch the robo drupal project folder name to "local".

**Comment by bdimaggio** [comment]
Ah! That makes sense. Okay, I'll do that work over in the robo repo, then.

**Comment by mariacha** [comment]
@bdimaggio bringing this one up again because it looks like if you're on Drupal 8.8, adding "devel" to the `config_exclude_modules` options also solves this. See this: https://github.com/thinkshout/encp-covid/commit/8eafc869bc1b0ab89893f306147dd237ef811448

**Pull request closed without merging**
