### PR TITLE
Issue #17 using sql dump and terminus instead of sql-sync on pantheon…

### PR DESCRIPTION
**Pull request by mariacha**
…. Hiding tantalizing .idea files from git.

Works on #17

### CODE REVIEW

**Comment by mariacha** [comment]
Using this I got:

```
PROMPT set to '/Users/mariafisher/.composer/global/pantheon-systems/terminus/vendor/pantheon-systems/terminus/src/Terminus.php:103'
mysql: Character set 'omponentConsoleApplication->run()' is not a compiled character set and is not specified in the '/usr/local/Cellar/mariadb/10.3.9/share/mysql/charsets/Index.xml' file
mysql: Character set 'omponentConsoleApplication->doRun()' is not a compiled character set and is not specified in the '/usr/local/Cellar/mariadb/10.3.9/share/mysql/charsets/Index.xml' file
mysql: Character set 'omponentConsoleApplication->doRunCommand()' is not a compiled character set and is not specified in the '/usr/local/Cellar/mariadb/10.3.9/share/mysql/charsets/Index.xml' file
ERROR at line 16214: Unknown command '\A'.
SQL client error occurred.
```

**Comment by mariacha** [comment]
The reason for above is that Terminus is spitting out this warning:

```
 [warning] This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first
```

which is corrupting my sql dump. Thanks terminus.

**Comment by mariacha** [comment]
@mortenson Heads up -- Since I needed it for HSUS, I made a PR for this sql-sync -> sql-dump workflow in robo-drupal. Bummer is that it didn't work with terminus because terminus was outputting some junk in front of the sql dump.

**Comment by mortenson** [comment]
@mariacha Sorry it took me so long :) Looks good to me.

**Pull request merged**
